root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/auto_park ./cmd/auto_park"
bin = "./tmp/auto_park"
include_ext = ["go", "sql", "env"]
exclude_dir = ["tmp", "vendor"]
delay = 1000
stop_on_error = true

[log]
time = true
