package swagger

import "github.com/gin-gonic/gin"

const spec = `{
  "openapi": "3.0.3",
  "info": {
    "title": "Auto Park API",
    "version": "1.0.0",
    "description": "Modular monolith API for users, vehicles, tires, tire places, tripsheets and tripsheet trips. All endpoints run on a single server port 8080."
  },
  "servers": [{"url": "/"}],
  "components": {
    "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}},
    "schemas": {
      "ErrorResponse": {"type": "object", "properties": {"success": {"type": "boolean", "example": false}, "error": {"type": "string", "example": "validation error"}}},
      "LoginRequest": {"type": "object", "required": ["email", "password"], "properties": {"email": {"type": "string", "example": "admin@autopark.local"}, "password": {"type": "string", "example": "secret"}}},
      "VehicleCreateRequest": {"type": "object", "properties": {"brand": {"type": "string"}, "model": {"type": "string"}, "year": {"type": "integer"}, "vin": {"type": "string"}, "state_number": {"type": "string"}, "board_number": {"type": "string"}, "received_date": {"type": "string", "format": "date-time"}, "drivers_ids": {"type": "array", "items": {"type": "integer"}}}},
      "TireRequest": {"type": "object", "properties": {"place_id": {"type": "integer"}, "vehicle_id": {"type": "integer", "nullable": true}, "tire": {"type": "string"}, "mileage": {"type": "integer"}, "max_usage": {"type": "integer"}}},
      "TirePlaceRequest": {"type": "object", "required": ["name"], "properties": {"name": {"type": "string"}}},
      "TripsheetRequest": {"type": "object", "properties": {"tripsheet_number": {"type": "string"}, "tripsheet_date": {"type": "string", "format": "date"}, "vehicle_id": {"type": "integer", "nullable": true}, "vehicle_brand": {"type": "string"}, "vehicle_plate_number": {"type": "string"}, "driver_id": {"type": "integer", "nullable": true}, "driver_last_name": {"type": "string"}, "driver_first_name": {"type": "string"}, "driver_middle_name": {"type": "string"}, "departure_time": {"type": "string", "format": "date-time", "nullable": true}, "return_time": {"type": "string", "format": "date-time", "nullable": true}, "mileage_start": {"type": "integer"}, "mileage_end": {"type": "integer"}, "fuel_start": {"type": "number"}, "fuel_issued": {"type": "number"}, "fuel_consumption_theoretical": {"type": "number"}, "fuel_consumption_actual": {"type": "number"}, "status_id": {"type": "integer"}}},
      "TripsheetTripRequest": {"type": "object", "properties": {"tripsheet_id": {"type": "integer"}, "route_description": {"type": "string"}, "start_time": {"type": "string", "format": "date-time", "nullable": true}, "end_time": {"type": "string", "format": "date-time", "nullable": true}, "distance_passed": {"type": "integer", "nullable": true}, "status_id": {"type": "integer"}}}
    }
  },
  "paths": {
    "/healthz": {"get": {"tags": ["System"], "summary": "Health check", "responses": {"200": {"description": "OK"}}}},
    "/api/users/login": {"post": {"tags": ["Users"], "summary": "Login", "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LoginRequest"}}}}, "responses": {"200": {"description": "JWT token"}, "401": {"description": "Unauthorized"}}}},
    "/api/users": {"get": {"tags": ["Users"], "summary": "List users", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "User list"}}}, "post": {"tags": ["Users"], "summary": "Create user", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"201": {"description": "User created"}}}},
    "/api/users/{id}": {"get": {"tags": ["Users"], "summary": "Get user by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "User"}}}, "put": {"tags": ["Users"], "summary": "Update user", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Users"], "summary": "Delete user", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/users/drivers": {"get": {"tags": ["Drivers"], "summary": "List drivers", "security": [{"bearerAuth": []}], "parameters": [{"name": "limit", "in": "query", "schema": {"type": "integer"}}, {"name": "offset", "in": "query", "schema": {"type": "integer"}}, {"name": "search", "in": "query", "schema": {"type": "string"}}, {"name": "status", "in": "query", "schema": {"type": "string"}}, {"name": "board_number", "in": "query", "schema": {"type": "string"}}, {"name": "sort_by", "in": "query", "description": "Sort by: id, surname, name, iin, board_number, status, created_at, updated_at", "schema": {"type": "string"}}, {"name": "order", "in": "query", "description": "Sort order: asc or desc", "schema": {"type": "string"}}, {"name": "include_archived", "in": "query", "schema": {"type": "boolean", "default": false}}], "responses": {"200": {"description": "Driver list"}}}, "post": {"tags": ["Drivers"], "summary": "Create driver", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"201": {"description": "Created"}}}},
    "/api/users/drivers/{id}": {"get": {"tags": ["Drivers"], "summary": "Get driver by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Driver"}}}, "put": {"tags": ["Drivers"], "summary": "Update driver", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"type": "object"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Drivers"], "summary": "Archive driver", "description": "Archives driver without physical deletion.", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Archived"}}}},
    "/api/vehicles": {"get": {"tags": ["Vehicles"], "summary": "List vehicles", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "Vehicle list"}}}, "post": {"tags": ["Vehicles"], "summary": "Create vehicle", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/VehicleCreateRequest"}}}}, "responses": {"201": {"description": "Vehicle created"}}}},
    "/api/vehicles/{id}": {"get": {"tags": ["Vehicles"], "summary": "Get vehicle by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Vehicle"}}}, "put": {"tags": ["Vehicles"], "summary": "Update vehicle", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/VehicleCreateRequest"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Vehicles"], "summary": "Delete vehicle", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/vehicles/tires": {"get": {"tags": ["Tires"], "summary": "List tires", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "Tire list"}}}, "post": {"tags": ["Tires"], "summary": "Create tire", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TireRequest"}}}}, "responses": {"201": {"description": "Tire created"}}}},
    "/api/vehicles/tires/{id}": {"get": {"tags": ["Tires"], "summary": "Get tire by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Tire"}}}, "put": {"tags": ["Tires"], "summary": "Update tire", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TireRequest"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Tires"], "summary": "Delete tire", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/vehicles/vehicle-tires/{vehicle_id}": {"get": {"tags": ["Tires"], "summary": "Get tires by vehicle ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "vehicle_id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Tires for vehicle"}}}},
    "/api/vehicles/tire-places": {"get": {"tags": ["Tire Places"], "summary": "List tire places", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "Tire places list"}}}, "post": {"tags": ["Tire Places"], "summary": "Create tire place", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TirePlaceRequest"}}}}, "responses": {"201": {"description": "Created"}}}},
    "/api/vehicles/tire-places/{id}": {"get": {"tags": ["Tire Places"], "summary": "Get tire place by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Tire place"}}}, "put": {"tags": ["Tire Places"], "summary": "Update tire place", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TirePlaceRequest"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Tire Places"], "summary": "Delete tire place", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/tripsheet/health": {"get": {"tags": ["Tripsheets"], "summary": "Tripsheet module health", "responses": {"200": {"description": "OK"}}}},
    "/api/tripsheet": {"get": {"tags": ["Tripsheets"], "summary": "List tripsheets", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "Tripsheet list"}}}, "post": {"tags": ["Tripsheets"], "summary": "Create tripsheet", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TripsheetRequest"}}}}, "responses": {"201": {"description": "Created"}}}},
    "/api/tripsheet/{id}": {"get": {"tags": ["Tripsheets"], "summary": "Get tripsheet by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Tripsheet"}}}, "put": {"tags": ["Tripsheets"], "summary": "Update tripsheet", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TripsheetRequest"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Tripsheets"], "summary": "Delete tripsheet", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/tripsheet/trips": {"get": {"tags": ["Tripsheet Trips"], "summary": "List tripsheet trips", "security": [{"bearerAuth": []}], "responses": {"200": {"description": "Trip list"}}}, "post": {"tags": ["Tripsheet Trips"], "summary": "Create tripsheet trip", "security": [{"bearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TripsheetTripRequest"}}}}, "responses": {"201": {"description": "Created"}}}},
    "/api/tripsheet/trips/{id}": {"get": {"tags": ["Tripsheet Trips"], "summary": "Get tripsheet trip by ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Trip"}}}, "put": {"tags": ["Tripsheet Trips"], "summary": "Update tripsheet trip", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TripsheetTripRequest"}}}}, "responses": {"200": {"description": "Updated"}}}, "delete": {"tags": ["Tripsheet Trips"], "summary": "Delete tripsheet trip", "security": [{"bearerAuth": []}], "parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Deleted"}}}},
    "/api/tripsheet/trips/by-tripsheet/{tripsheet_id}": {"get": {"tags": ["Tripsheet Trips"], "summary": "Get all trips by tripsheet ID", "security": [{"bearerAuth": []}], "parameters": [{"name": "tripsheet_id", "in": "path", "required": true, "schema": {"type": "integer"}}], "responses": {"200": {"description": "Trips for tripsheet"}}}}
  }
}`

func Register(r *gin.Engine) {
	r.GET("/swagger/doc.json", func(c *gin.Context) {
		c.Data(200, "application/json; charset=utf-8", []byte(spec))
	})
}
